### ISSUE TITLE
MultiParamTypeClasses explanation

### ISSUE THREAD

**Issue by elliotdavies** [i-am-tom/haskell-exercises#7]
A few notes on the MPTC explanation while I remember:

- https://github.com/i-am-tom/haskell-exercises/blob/master/exercise09/src/MultiParamTypeClasses.hs#L178 - I don't think this series of steps quite makes sense: if we have a winner here (at 3) one way or the other then what are 4 or 5 for?
- https://github.com/i-am-tom/haskell-exercises/blob/master/exercise09/src/MultiParamTypeClasses.hs#L202 - This line compiles just fine, because there's only one `Sneaky` instance, but the text suggests it will fail (and the explanation for why, on L213, refers to `Transform` rather than `Sneaky`)
- https://github.com/i-am-tom/haskell-exercises/blob/master/exercise09/src/MultiParamTypeClasses.hs#L224 - I'm confused by the parenthesised clause  in this sentence; it's very abrupt

**Comment by elliotdavies** [comment]
Also...

- I found it a bit hard to reason about exercise 3 because of the name of `SmallerThan`
- On exercise 4c the wording initially led me to think I needed to convert between `Equal a b` and `a ~ b`, though of course you intended that I convert between `a` and `b`, and that makes a lot more sense
- On exercise 10 I think `author :: Int` in the definition of `Comment` should be `UserID` for the sake of a prettier example
- Also on exercise 10, `Status` doesn't seem to be used anywhere

**Comment by elliotdavies** [comment]
Thoughts after reviewing the solutions
- Better exercise than `Appendable`
- Reconsider strong wording

**Comment by i-am-tom** [comment]
FINALLY getting round to this 💪 

1. Rule 3 doesn't apply if I have more than one matching non-INCOHERENT instance.

2. The later INCOHERENT instance fixes the problem :( I've commented it, so that should trigger the error.

3. I've changed this text, hopefully a little less abrupt!

4. Just going to call it Fin, as it makes it much easier to google, too...

5. Added explicit signatures for the two functions.

6. Int -> UserId

7. Status is in the type signature of UserCache - not suuuuuper useful, but maybe makes the exercise more "real world"? idk about this one

8. Wrote a better example using `take` as an example function to implement.

9. Updated!
